kind = "mobile"
previewPath = "/"
title = "Raj Hotel"
version = "1.0.0"
id = "artifacts/raj-hotel"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
localPort = 18825
name = "expo"
paths = ["/"]

[services.development]
run = "pnpm --filter @workspace/raj-hotel run dev"

[services.env]
PORT = "18825"
BASE_PATH = "/"

[services.production]
build = ["pnpm", "--filter", "@workspace/raj-hotel", "run", "build"]
run = ["pnpm", "--filter", "@workspace/raj-hotel", "run", "serve"]
